### ISSUE TITLE
Register to MLRG

### ISSUE THREAD

**Issue by blaforge** [alopezso/Machine-Learning#5]
http://www.meetup.com/fr-FR/Paris-Machine-Learning-Reading-Group/events/228061518/?eventId=228061518&rv=ea1&rv=ea1

Create a account in meetup.com and apply to the Machine learning reading group

Next month the studied paper is may-be interesting.

[vinodicann.pdf](https://files.zenhub.io/569e22ea6387ff8d1f049864)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by alopezso** [comment]
Fait !
